services:
  - type: web
    name: bharati-unique-backend-v41
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DHAN_CLIENT_ID
        sync: false
      - key: DHAN_PIN
        sync: false
      - key: DHAN_TOTP_SECRET
        sync: false
      - key: DHAN_ACCESS_TOKEN
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_SUBJECT
        value: mailto:alerts@example.com
      - key: DEFAULT_INDEX
        value: NIFTY
      - key: MAX_TICKS_PER_INSTRUMENT
        value: "3000"
      - key: MAX_CANDLES_PER_INSTRUMENT
        value: "2000"
      - key: TICK_STALE_MS
        value: "15000"
      - key: LIVE_HISTORY_REFRESH_MS
        value: "10000"
      - key: CANDLE_TIMEFRAME_MS
        value: "60000"
      - key: OPTION_CHAIN_REFRESH_MS
        value: "3200"
      - key: DEPTH_MAX_INSTRUMENTS
        value: "50"
      - key: NIFTY_SECURITY_ID
        value: "13"
      - key: BANKNIFTY_SECURITY_ID
        value: "25"
      - key: FINNIFTY_SECURITY_ID
        value: "27"
      - key: MIDCPNIFTY_SECURITY_ID
        value: "442"
      - key: SENSEX_SECURITY_ID
        value: "51"
